package com.hospitalclaim.fraud.events

case class RawClaimEvent(datetime: String,
                         claim_id: String,
                         hour: String,
                         date: String,
                         month: String,
                         year: String,
                         patient_id: String,
                         patient_name: String,
                         patient_age: Long,
                         patient_gender: String,
                         patient_state_code: String,
                         patient_state_name: String,
                         patient_city_name: String,
                         patient_city_code: String,
                         hospital_id: String,
                         hospital_name: String,
                         hospital_state_name: String,
                         hospital_state_code: String,
                         hospital_city_name: String,
                         hospital_city_code: String,
                         claim_type: String,
                         claim_amount: Double,
                         diagnosis_id: String,
                         procedure_name: String,
                         procedure_type: String,
                         doctor_id: String)
